development:
  adapter: postgresql
  encoding: unicode
  database: personal-page_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: personal-page_test
  pool: 5
  username: postgres
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: personal-page_production
  pool: 5
  username: postgres
  password: password
  host: localhost
